- id: openai_news
  name: "OpenAI News"
  type: rss
  url: "https://openai.com/news/rss.xml"
  priority_weight: 1.0
  signal_type: ecosystem

- id: hn_rss
  name: "Hacker News"
  type: rss
  url: "https://news.ycombinator.com/rss"
  priority_weight: 0.7
  signal_type: ecosystem

- id: anthropic_news_proxy
  name: "Anthropic News (md_proxy via Jina Reader)"
  type: md_proxy
  url: "https://r.jina.ai/https://www.anthropic.com/news"
  priority_weight: 0.9
  signal_type: capability

- id: arxiv_ai
  name: "arXiv AI Research"
  type: arxiv_api
  url: "http://export.arxiv.org/api/query"
  query: "cat:cs.AI+OR+cat:cs.LG"
  priority_weight: 0.7
  signal_type: research
