import json
from pathlib import Path

from kb_manager.vault_ops import KnowledgeBaseManager
from pm_os_contracts.models import LTI_NODE, COS_CASE, LPL_POST


def main():
    repo_root = Path(__file__).resolve().parents[1]
    vault_root = repo_root / ".vault_test"
    vault_root.mkdir(parents=True, exist_ok=True)

    gate_path = repo_root / "tests" / "fixtures" / "gate_decision.json"
    gate = json.loads(gate_path.read_text(encoding="utf-8"))

    kb = KnowledgeBaseManager(vault_root=vault_root)

    task_id = gate["task_id"]
    reason = gate.get("decision_reason", "Writeback test")

    # 1) LTI writeback (uses your required id pattern ^LTI-[0-9]\.[0-9]+$)
    lti = LTI_NODE(
        id="LTI-3.0",
        status="active",
        title="Writeback Test Artifact (LTI)",
        series="v3.0-writeback-test",
        tags=["test"],
        source_task_id=task_id,
        summary=reason,
    )
    lti_path = kb.writeback_lti(lti)
    print(f"LTI OK: {lti_path}")
    assert lti_path.exists(), f"Missing LTI file: {lti_path}"

    # 2) COS writeback (required: id, task_id, failure_pattern_id)
    cos = COS_CASE(
        id="COS-20260216-001",
        task_id=task_id,
        failure_pattern_id="FP-TEST-001",
        blocked_by_gate_reason=reason,
        blocking_dimension="correctness",
        linked_rti=["RTI-TEST-001"],
    )
    cos_path = kb.writeback_cos(cos)
    print(f"COS OK: {cos_path}")
    assert cos_path.exists(), f"Missing COS file: {cos_path}"

    # 3) LPL writeback (required: id, source_lti_id, content)
    lpl = LPL_POST(
        id="LPL-20260216T130000Z-001",
        source_lti_id=lti.id,
        content="This is a test LPL post content generated by the writeback runner.",
        echo_score=0.0,
        engagement_stats={"likes": 0, "comments": 0, "reposts": 0},
    )
    lpl_path = kb.writeback_lpl(lpl)
    print(f"LPL OK: {lpl_path}")
    assert lpl_path.exists(), f"Missing LPL file: {lpl_path}"

    print("ALL WRITEBACKS PASSED ✅")


if __name__ == "__main__":
    main()
